[env:seeed_xiao_nrf52840_sense]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-afruitnrf52-nrf52840-sense
framework = arduino

lib_deps =
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit SSD1306@^2.5.9
    adafruit/Adafruit BusIO@^1.16.1
    https://github.com/Seeed-Studio/Seeed_Arduino_LSM6DS3.git#v2.0.7

monitor_speed = 115200

build_flags =
    -DARDUINO_NRF52_ADAFRUIT
    -Os

build_src_filter =
    +<*>
    +<hal/*>
    +<app/*>
